#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
# xmodmap "/home/hal/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

# Synaptic Touchpad
# if command -v synclient; then
#   synclient VertEdgeScroll=1
#   # synclient HorizEdgeScroll=1
#   synclient TapButton1=1
# fi

# Prelude
/usr/libexec/polkit-gnome-authentication-agent-1 &

# Start FluxBox
fluxbox &
fbpid=$!

command -v xcompmgr && (xcompmgr -c &)
command -v nitrogen && (nitrogen --restore &)
command -v conky    && (conky &)

command -v gnome-screensaver  && (gnome-screensaver &)
command -v nm-applet          && (nm-applet &)
command -v volumeicon         && (volumeicon &)

command -v gnome-power-manager && (gnome-power-manager &)
command -v bluetooth-applet    && (bluetooth-applet &)

wait $fbpid
# Cleanup
