#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change the resolution
xrandr -s 1920x1080

# Change your keymap:
# xmodmap "/home/hal/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

# Synaptic Touchpad
# if command -v synclient; then
#   synclient VertEdgeScroll=1
#   # synclient HorizEdgeScroll=1
#   synclient TapButton1=1
# fi

# Applications ENV variables
export TERMINAL="gnome-terminal"
export FILE_MANAGER="nautilus --no-desktop"
export GUI_EDITOR="gvim"
export BROWSER="chromium-browser"
export EMAIL_CLIENT="evolution"
export IM_CLIENT="pidgin"
export IRC_CLIENT="hexchat --no-plugins"
export MUSIC_PLAYER="rhythmbox"
export VIDEO_PLAYER="mpv"
export TORRENT_CLIENT="transmission-gtk"
export DOCUMENT_EDITOR="libreoffice --writer"
export SPREADSHEET_EDITOR="libreoffice --calc"
export PRESENTATION_EDITOR="libreoffice --impress"

# Start FluxBox
fluxbox &
fbpid=$!

if   command -v compton;  then compton &
elif command -v xcompmgr; then xcompmgr -c &
fi
command -v nitrogen && (nitrogen --restore &)
command -v conky    && (conky &)

command -v gnome-screensaver  && (gnome-screensaver &)
command -v nm-applet          && (nm-applet &)
command -v volumeicon         && (volumeicon &)

command -v gnome-power-manager && (gnome-power-manager &)
command -v bluetooth-applet    && (bluetooth-applet &)

wait $fbpid
# Cleanup
