#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
# xmodmap "/home/hal/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

# Synaptic Touchpad
if [[ -x /usr/bin/synclient ]]; then
  synclient VertEdgeScroll=1
  # synclient HorizEdgeScroll=1
  synclient TapButton1=1
fi

[[ -x /usr/bin/xcompmgr ]] && (xcompmgr -c &)
[[ -x /usr/bin/nitrogen ]] && (nitrogen --restore &)
[[ -x /usr/bin/conky    ]] && (conky &)

gnome-screensaver &
nm-applet &
gnome-sound-applet &

[[ -x /usr/bin/gnome-power-manager ]] && (gnome-power-manager &)
[[ -x /usr/bin/bluetooth-applet    ]] && (bluetooth-applet &)

/usr/libexec/polkit-gnome-authentication-agent-1 &
eval $(gpg-agent --daemon)
eval $(gnome-keyring-daemon)

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/hal/.fluxbox/log"
